/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://kcfmrrzzni.execute-api.us-east-1.amazonaws.com/staging",
            "region": "us-east-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://ltfzjl7wezdffavsmswsebxzxe.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-6nuz3wnqg5e4rbslubtgsroqxq",
    "aws_cognito_identity_pool_id": "us-east-1:c8dea3bc-1b02-4cbc-bed7-864a54b79d75",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_IABR8YZi2",
    "aws_user_pools_web_client_id": "7knoil6cchjs2998q4vcqts4uo",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "elderlyapp-storage-40e3a6fd7ef92-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
